name: Generate osqueryd.app.tar.gz for Orbit

on:
  push:
    branches:
      - main
    paths:
      # The workflow can be triggered by modifying OSQUERY_VERSION env
      # below and pushing/merging to main.
      - '.github/workflows/generate-osqueryd-app-tar-gz.yml'
  workflow_dispatch:

permissions:
  contents: write

env:
  OSQUERY_VERSION: 5.2.2

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate osqueryd.app.tar.gz
        run: |
          make osqueryd-app-tar-gz out-path=. version=$OSQUERY_VERSION

      - name: Release
        if: hashFiles('osqueryd.app.tar.gz') != ''
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v0.1.14
        with:
          files: "osqueryd.app.tar.gz"
          tag_name: ${{ env.ETAG }}
          token: ${{ secrets.GITHUB_TOKEN }}